server:
  port: 8083

spring:
  application:
    name: payment-service

seata:
  enabled: true
  application-id: payment-service
  tx-service-group: payment_tx_group
  service:
    vgroup-mapping:
      payment_tx_group: default
    grouplist:
      default: 127.0.0.1:8091  # your Seata server address
  config:
    type: file
  registry:
    type: file
