server:
  port: 8082

spring:
  application:
    name: inventory-service

seata:
  enabled: true
  application-id: inventory-service
  tx-service-group: inventory_tx_group
  service:
    vgroup-mapping:
      inventory_tx_group: default
    grouplist:
      default: 127.0.0.1:8091  # your Seata server address
  config:
    type: file
  registry:
    type: file
